{ pkgs, inputs, self, ... }: {
  nixpkgs = { inherit (self.nixpkgs) config overlays; };

  imports = [
    inputs.nixos-wsl.nixosModules.default
    inputs.home-manager.nixosModules.default
  ];

  system.stateVersion = "25.05";
  nixpkgs.hostPlatform = "x86_64-linux";

  wsl.enable = true;
  wsl.defaultUser = "reyhan";
  wsl.docker-desktop.enable = true;

  # WSL networking configuration for VPN compatibility
  wsl.wslConf = {
    network = {
      generateHosts = false;
      generateResolvConf = false; # Disable auto DNS to manually manage VPN DNS
    };
    automount.options = "metadata,uid=1000,gid=100";
  };

  # Manual DNS configuration (will be managed by a script)
  networking.nameservers = [ "8.8.8.8" "8.8.4.4" ]; # Fallback DNS
  networking.resolvconf.enable = true;

  # Helper script to sync Windows DNS to WSL (for VPN)
  environment.systemPackages = with pkgs; [
    (writeShellScriptBin "wsl-vpn-sync" ''
      #!/usr/bin/env bash
      # Sync Windows DNS servers to WSL for VPN connectivity

      echo "Syncing Windows DNS to WSL..."

      # Get DNS servers from Windows
      WIN_DNS=$(powershell.exe -Command "(Get-DnsClientServerAddress -AddressFamily IPv4 | Where-Object {$_.ServerAddresses}).ServerAddresses" 2>/dev/null | tr -d '\r' | grep -v '^$')

      if [ -z "$WIN_DNS" ]; then
        echo "Warning: Could not retrieve Windows DNS servers"
        echo "Using fallback DNS: 8.8.8.8, 8.8.4.4"
        WIN_DNS="8.8.8.8
8.8.4.4"
      fi

      # Write to resolv.conf
      echo "# Generated by wsl-vpn-sync" > /etc/resolv.conf
      echo "# $(date)" >> /etc/resolv.conf
      echo "$WIN_DNS" | while read -r dns; do
        if [ -n "$dns" ]; then
          echo "nameserver $dns" >> /etc/resolv.conf
          echo "Added nameserver: $dns"
        fi
      done

      echo "DNS sync complete!"
    '')
  ];

  # Automatic DNS sync service - runs on boot and periodically
  systemd.services.wsl-vpn-dns-sync = {
    description = "Sync Windows DNS to WSL for VPN connectivity";
    wantedBy = [ "multi-user.target" ];
    after = [ "network.target" ];

    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${pkgs.writeShellScript "wsl-vpn-sync-service" ''
        #!/usr/bin/env bash

        # Get DNS servers from Windows
        WIN_DNS=$(powershell.exe -Command "(Get-DnsClientServerAddress -AddressFamily IPv4 | Where-Object {\$_.ServerAddresses}).ServerAddresses" 2>/dev/null | tr -d '\r' | grep -v '^$')

        if [ -z "$WIN_DNS" ]; then
          # Fallback to Google DNS
          WIN_DNS="8.8.8.8
8.8.4.4"
        fi

        # Write to resolv.conf
        {
          echo "# Generated by wsl-vpn-dns-sync service"
          echo "# $(date)"
          echo "$WIN_DNS" | while read -r dns; do
            if [ -n "$dns" ]; then
              echo "nameserver $dns"
            fi
          done
        } > /etc/resolv.conf

        logger "WSL VPN DNS sync completed"
      ''}";
      RemainAfterExit = true;
    };
  };

  # Optional: Periodic DNS sync timer (every 5 minutes)
  # Uncomment to enable automatic periodic syncing
  # systemd.timers.wsl-vpn-dns-sync = {
  #   wantedBy = [ "timers.target" ];
  #   timerConfig = {
  #     OnBootSec = "1min";
  #     OnUnitActiveSec = "5min";
  #     Unit = "wsl-vpn-dns-sync.service";
  #   };
  # };

  home-manager.useGlobalPkgs = true;
  home-manager.useUserPackages = true;

  nix.settings = {
    nix-path = [ "nixpkgs=${inputs.nixpkgs}" ];
    experimental-features = [ "flakes" "nix-command" ];
  };

  # virtualisation.virtualbox.host.enable = true;
  # virtualisation.virtualbox.host.enableExtensionPack = true;

  services.dbus.enable = true;

  # environment.systemPackages = [ inputs.nixpkgs-master.claude-code ];
  environment.shells = with pkgs; [ zsh ];
  # environment.variables = { VAGRANT_WSL_ENABLE_WINDOWS_ACCESS = "1"; };

  networking.hostName = "nixos";
  networking.extraHosts = "192.168.0.157 ubuntu.local";

  users.users.reyhan = {
    shell = pkgs.zsh;
    home = "/home/reyhan";
  };
  programs.zsh.enable = true;

  fonts.fontDir.enable = true;
  fonts.packages = with pkgs; [
    nerd-fonts.fira-code
    nerd-fonts.droid-sans-mono
    nerd-fonts.hack
  ];
}

